#!/bin/bash -

#RED='\033[0;31m'
#GREEN='\033[0;32m'
#NC='\033[0m' # No Color

error_config()
{
  #printf "${RED}"
  echo "postbuild script failed"
  echo "====="
  if [ -z $1 ]; then
    echo "===== Error occurred."
  else
    echo "===== Error occurred. ($1)"
  fi
  echo "===== See $current_log_file for details. Then try again."
  echo "====="
  if [ "$script_mode" != "AUTO" ]; then $SHELL; fi
  exit 1
}

sucess_config()
{
  rm "$current_log_file"
  #printf "${GREEN}"
  echo "postbuild script success"
  echo

  # ============================================================= End functions ===================================================
  # All the steps were executed correctly
  #printf "${NO}"
  if [ "$mode" != "AUTO" ]; then $SHELL; fi
  exit 0
}


install_package()
{
  echo "Please get STM32H5 Secure Manager package from st.com." |tee -a "$current_log_file"
  error_config "env"
}


##########################
#  post_build.sh
##########################
# Environment variables for log files
thispath=$(cd "$(dirname "$0")" && pwd)
applidir=$(cd "$(dirname "$0")" && pwd)
config=$*

## print appli dir
echo "applidir: $applidir"

# Getting the Trusted Package Creator and STM32CubeProgammer CLI path
if [[ -z "$stm32tpccli" ]] || [[ -z "$sm_ns_app_boot_path_project" ]]; then
  if [ -e "$applidir/env.sh" ]; then
    source "$applidir/env.sh" 2>/dev/null
  else
    echo "env.sh missing"
    install_package
  fi
fi
current_log_file="$thispath/postbuild.log"
echo "Generated by sh"> $current_log_file

#Copy SMAK Appli binary to Binary location
cp -p "$applidir/../build/$config/ml_model_attestation.bin" "$applidir/../Binary/appli.bin" >> "$current_log_file" 2>&1
if [ $? -ne 0 ]; then
  error_config 'copy';
else
  echo "file is copied"
fi

image_path=$(cygpath -w "$applidir/../Images/SM_Code_Image.xml")
"$stm32tpccli" -pb "$image_path" >> "$current_log_file" 2>&1

echo "applidir: $applidir/../Images/SM_Code_Image.xml"
if [ $? -ne 0 ]; then
  error_config 'image';
fi

image_bin_path=$(cygpath -w "$applidir/../Images/SM_Code_Image_bin.xml")
"$stm32tpccli" -pb "$image_bin_path" >> "$current_log_file" 2>&1
if [ $? -ne 0 ]; then
  error_config 'bin';
else
  sucess_config
fi
